import Header from "@/components/Header";
import "@/styles/global.scss";
import type { Metadata } from "next";
import {
  Montserrat_Alternates,
  Roboto_Mono,
  Space_Grotesk,
} from "next/font/google";

const AlternatesItalic = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["500", "600"],
  style: "italic",
  variable: "--font-alternates",
});

const openSans = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-openSans",
});

// TODO: Averifier si on garde ou non

// const titleFont = localFont({
//   src: "../styles/fonts/foobar_pro/FoobarPro-Regular.ttf.woff",
//   weight: "500",
//   style: "normal",
//   variable: "--font-foobar",
// });

const titleFont = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-titleFont",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${titleFont.variable} ${AlternatesItalic.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
