import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/global.scss';
import BackgroundImage from '@/components/BackgroundImage';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        <BackgroundImage />
      </body>
    </html>
  );
}
